name: NX Affected Build


on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Affected Matrix
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Calculate affected projects
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          targets: 'test,build'
          maxDistribution: 3
          workingDirectory: ''
          args: ''

  execute:
    name: ${{ matrix.target }}
    if: ${{ fromJSON(needs.setup.outputs.hasChanges) }}
    needs: [setup]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.target == 'test' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      # Checkout, cache, install node modules

      - name: Execute
        uses: e-square-io/nx-distributed-task@v2
        id: execute
        with:
          target: ${{ matrix.target }}
          projects: ${{ matrix.projects }}
          uploadOutputs: true
          nxCloud: false
          args: ''
