name: NX Scrape Matrix


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Scrape NX for projects
    outputs:
      matrix: ${{ steps.scripting.outputs.affectedJSON }}
      apps: ${{ steps.apps.outputs.affectedApps }}
      array-apps: ${{ steps.array-apps.outputs.affectedAppsArray }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        id: setSHAs
      - uses: actions/github-script@v6
        id: scripting
        with:
          script: |
            const execSync = require('child_process').execSync;
            let include = [];
            let runner_task = {};
            let nxJson = JSON.parse(execSync(`npx nx print-affected --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --target=build-android`).toString().trim())
            nxJson.tasks.forEach(task => {
              let runner_task = {
                id: task.id,
                project: task.target.project,
                target: task.target.target,
                command: task.command,
                outputs: task.outputs
              }
              include.push(runner_task);
            });
            let json={};
            json["include"] = include;
            let ready = JSON.stringify(json);
            core.setOutput('affectedJSON', ready);
      - name: Print json
        run: echo "${{ steps.scripting.outputs.affectedJSON }}"
      - uses: actions/github-script@v6
        id: apps
        with:
          script: |
            const execSync = require('child_process').execSync;
            let apps = execSync(`npx nx print-affected --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --target=build-android --type=app`).toString().trim()
            core.setOutput("affectedApps", apps);
      - uses: actions/github-script@v6
        id: array-apps
        with:
          script: |
            const execSync = require('child_process').execSync;
            let apps = execSync(`npx nx print-affected --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --target=build-android --select=tasks.target.project`).toString().trim()
            core.setOutput("affectedAppsArray", apps);
#      - name: Generate affected matrix
#        uses: mathiasvr/command-output@v1
#        continue-on-error: true
#        id: cmd
#        with:
#          run: npx nx print-affected --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --target=build-android
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml


  json_custom_execute:
    name: BUILD the json
    needs: [matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: npm install -g nx
      - run: yarn install
      - run: nx run ${{ matrix.project }}:${{ matrix.target}}
